export default [
  {
    _id: "121",
    username: "stellar_voyager",
    password: "explorer88",
    firstName: "Max",
    lastName: "Sterling",
    email: "max88@space.com",
    dob: "1988-03-21",
    role: "STUDENT",
  },
  {
    _id: "122",
    username: "night_hawk",
    password: "shadow234",
    firstName: "John",
    lastName: "Carter",
    email: "johnny@carter.com",
    dob: "1991-07-15",
    role: "STUDENT",
  },
  {
    _id: "123",
    username: "patriot_echo",
    password: "freedom123",
    firstName: "Sam",
    lastName: "Wilson",
    email: "sam.wilson@freedom.com",
    dob: "1990-04-30",
    role: "STUDENT",
  },
  {
    _id: "124",
    username: "red_spy",
    password: "clandestine321",
    firstName: "Irina",
    lastName: "Sparrow",
    email: "irina.spy@network.com",
    dob: "1986-10-11",
    role: "STUDENT",
  },
  {
    _id: "125",
    username: "storm_chaser",
    password: "thunder456",
    firstName: "Liam",
    lastName: "Stone",
    email: "liam@storm.com",
    dob: "1992-01-18",
    role: "STUDENT",
  },
  {
    _id: "126",
    username: "green_giant",
    password: "peaceful12",
    firstName: "Henry",
    lastName: "Kale",
    email: "henry.kale@green.com",
    dob: "1978-11-09",
    role: "STUDENT",
  },
  {
    _id: "127",
    username: "small_wonder",
    password: "tinyhero999",
    firstName: "Pippin",
    lastName: "Whitfoot",
    email: "pippin@hobbiton.com",
    dob: "1382-05-28",
    role: "FACULTY",
  },
  {
    _id: "128",
    username: "ranger_sable",
    password: "forestrunner213",
    firstName: "Eldarion",
    lastName: "Telcontar",
    email: "eldarion@middleearth.com",
    dob: "2951-06-23",
    role: "FACULTY",
  },
  {
    _id: "129",
    username: "mystic_archer",
    password: "elvenwise101",
    firstName: "Faelon",
    lastName: "Leafwind",
    email: "faelon@elvishrealm.com",
    dob: "2855-03-12",
    role: "FACULTY",
  },
];
